name: Run PleasureBot
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: |
          echo "TWITTER_USERNAME=${{ secrets.TWITTER_USERNAME }}" >> .env
          echo "TWITTER_PASSWORD=${{ secrets.TWITTER_PASSWORD }}" >> .env
          echo "TWITTER_EMAIL=${{ secrets.TWITTER_EMAIL }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      - run: pnpm build
      - run: pnpm start
